name: ci

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main

jobs:
  checks:
    if: ${{ ! github.event.pull_request.draft == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v6
        with:
          python-version: |
            3.10
            3.13
      - run: uv lock --check
        working-directory: natsext
      - run: uv run --python=3.13 ruff format --check .
        working-directory: natsext
      - run: uv run --python=3.13 ruff check .
        working-directory: natsext
      - run: uv run --python=3.13 ty check .
        working-directory: natsext
      - run: uv run --python=3.13 pytest .
        working-directory: natsext
      - run: uv run --python=3.10 pytest .
        working-directory: natsext
