name: ci

on:
  release:
    types:
      - prereleased
      - released

jobs:
  jestreamext-publish:
    if: ${{ ! github.event.pull_request.draft == true }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: astral-sh/setup-uv@v6
      - uses: actions/setup-python@v6
        with:
          python-version: |
            3.13
      - run: uv build
        working-directory: jestreamext
      - if: github.event.release.prerelease
        run: uv publish --index testpypi
        working-directory: jestreamext
      - if: ${{ ! github.event.release.prerelease }}
        run: uv publish
        working-directory: jestreamext
